---
golang/go1.6.1.linux-amd64.tar.gz:
  object_id: 6ed0fb3d-f52b-4255-a4da-6fa3e3e97194
  sha: c73492474dcc7a233772d27e948b74468d9f1849
  size: 84824395
consul/consul-template_0.14.0_linux_amd64.zip:
  object_id: 9658016c-ab14-4037-b859-d144fa9fc9e7
  sha: f932301f69a477253e4e4bf3c60159ea77cf28a8
  size: 3523492
consul/consul_0.6.4_linux_amd64.zip:
  object_id: de9ee191-b088-4cef-8c02-e68d4d16eb29
  sha: 85de555de27cae126f0f89e762f6136e1c7104b6
  size: 6206903
