iaas_settings:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  compilation_cloud_properties: {}
  resource_pool_cloud_properties:
    - name: consul_z1
      cloud_properties: {}
    - name: consul_z2
      cloud_properties: {}

  subnet_configs:
    - name: consul1
      subnets:
      - cloud_properties:
          name: random
        range: 10.244.4.0/30
        reserved:
        - 10.244.4.1
        static:
        - 10.244.4.2
      - cloud_properties:
          name: random
        range: 10.244.4.4/30
        reserved:
        - 10.244.4.5
        static:
        - 10.244.4.6
      - cloud_properties:
          name: random
        range: 10.244.4.8/30
        reserved:
        - 10.244.4.9
        static:
        - 10.244.4.10
      - cloud_properties:
          name: random
        range: 10.244.4.12/30
        reserved:
        - 10.244.4.13
        static:
        - 10.244.4.14
      - cloud_properties:
          name: random
        range: 10.244.4.16/30
        reserved:
        - 10.244.4.17
        static:
        - 10.244.4.18
    - name: consul2
      subnets:
      - cloud_properties:
          name: random
        range: 10.244.5.0/30
        reserved:
        - 10.244.5.1
        static:
        - 10.244.5.2
      - cloud_properties:
          name: random
        range: 10.244.5.4/30
        reserved:
        - 10.244.5.5
        static:
        - 10.244.5.6
      - cloud_properties:
          name: random
        range: 10.244.5.8/30
        reserved:
        - 10.244.5.9
        static:
        - 10.244.5.10
      - cloud_properties:
          name: random
        range: 10.244.5.12/30
        reserved:
        - 10.244.5.13
        static:
        - 10.244.5.14
      - cloud_properties:
          name: random
        range: 10.244.5.16/30
        reserved:
        - 10.244.5.17
        static:
        - 10.244.5.18
    - name: compilation
      subnets:
      - cloud_properties:
          name: random
        range: 10.244.6.0/30
        reserved:
        - 10.244.6.1
        static: []
      - cloud_properties:
          name: random
        range: 10.244.6.4/30
        reserved:
        - 10.244.6.5
        static: []
      - cloud_properties:
          name: random
        range: 10.244.6.8/30
        reserved:
        - 10.244.6.9
        static: []
